apiVersion: v1
kind: ReplicationController
metadata:
 name: test-rc
 labels:
  app: prod
  author: brlab
spec:
 replicas: 2
 selector:
  app: prod
  author: brlab
 template:
  metadata:
   name: test-web
   labels:
    app: prod
    author: brlab
    region: london
  spec:
   containers:
    - name : nginx-cont
      image: nginx
      ports:
       - containerPort: 80
